### ISSUE TITLE
Add-Migration Init

### ISSUE THREAD

**Issue by zanjs** [fuluteam/fulusso#1]
```ss
Add-Migration Init
Build started...
Build succeeded.
Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.1.9 initialized 'FuluDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: None
Your target project 'Fulu.Passport.Web' doesn't match your migrations assembly 'Fulu.Passport.Domain'. Either change your target project or change your migrations assembly.
Change your migrations assembly by using DbContextOptionsBuilder. E.g. options.UseSqlServer(connection, b => b.MigrationsAssembly("Fulu.Passport.Web")). By default, the migrations assembly is the assembly containing the DbContext.
Change your target project to the migrations project by using the Package Manager Console's Default project drop-down list, or by executing "dotnet ef" from the directory containing the migrations project.
```

**Comment by ich-wangxf** [comment]
> ```scheme
> Add-Migration Init
> Build started...
> Build succeeded.
> Microsoft.EntityFrameworkCore.Infrastructure[10403]
>       Entity Framework Core 3.1.9 initialized 'FuluDbContext' using provider 'Pomelo.EntityFrameworkCore.MySql' with options: None
> Your target project 'Fulu.Passport.Web' doesn't match your migrations assembly 'Fulu.Passport.Domain'. Either change your target project or change your migrations assembly.
> Change your migrations assembly by using DbContextOptionsBuilder. E.g. options.UseSqlServer(connection, b => b.MigrationsAssembly("Fulu.Passport.Web")). By default, the migrations assembly is the assembly containing the DbContext.
> Change your target project to the migrations project by using the Package Manager Console's Default project drop-down list, or by executing "dotnet ef" from the directory containing the migrations project.
> ```

是否是未设置默认项目？打开程序包管理器，切换默认项目为：Fulu.Passport.Web, 如下图所示：

![image](https://camo.githubusercontent.com/fa15ab872f69dc7a5aaf2c7336bbd9bcda5cd7769b1615cc888462f81cd3675d/68747470733a2f2f66756c752d6974656d31312d7a6a6b2e6f73732d636e2d7a68616e676a69616b6f752e616c6979756e63732e636f6d2f696d616765732f32303230313130363131313333342e706e67)

**Comment by zanjs** [comment]
![image](https://user-images.githubusercontent.com/12947276/98756152-f55e5000-2404-11eb-856e-f155d464af92.png)

**Comment by zanjs** [comment]
设置默认项目了 

![image](https://user-images.githubusercontent.com/12947276/98756295-3a828200-2405-11eb-90c3-00f524f4d15f.png)

**Comment by zanjs** [comment]
已经临时修改

```c#
 string conn = "server=127.0.0.1;Port=3306;Database=fulu;Uid=root;Pwd=qq111111";
            services.AddDbContext<T>(ops => ops.UseMySql(conn,
                    b => b.MigrationsAssembly("Fulu.Passport.Web")
            ));
```
