### ISSUE TITLE
net core 3.1这个月官方停止支持了。大佬，什么时候能切换下一个长期支持版net6？

### ISSUE THREAD

**Issue by gadgj** [fuluteam/fulusso#12]
如题！

**Comment by ich-wangxf** [comment]
> 如题！

identity server4 只免费支持.net core 3.1，新的Duende IdentityServer附带商业许可证

This organization is not maintained anymore besides critical security bugfixes (if feasible). This organization will be archived when .NET Core 3.1 end of support is reached (3rd Dec 2022). All new development is happening in the new Duende Software organization.

The new Duende IdentityServer comes with a commercial license but is free for dev/testing/personal projects and companies or individuals making less than 1M USD gross annnual revenue. Please get in touch with us if you have any question.
