### ISSUE TITLE
测试单点登录出了点问题？

### ISSUE THREAD

**Issue by langhaoabcd** [fuluteam/fulusso#7]
先登录了WebSample客户端，然后用户中心没有自动登入，单点登录是不是有点问题，
登出也是一样，程序中不同的客户端都生成了不一样的token, 统一登出登不出去了？
![image](https://user-images.githubusercontent.com/39892654/109412656-33977380-79e4-11eb-905f-1e892ba8528f.png)

**Comment by billsking** [comment]
因为各个客户端保持登录状态是使用的jwt，所以当登出的时候，如果jwt没有过期，那对应的客户端是不会自动登出了，除非指定的客户端主动去换取新的jwt。  同样的道理，客户端A登录了，用户中心其实是可以不用输入用户密码再登录的，只需要使用Oauth2.0协议，去获取用户中心自己的jwt就行了。

**Comment by langhaoabcd** [comment]
好的
